### ISSUE TITLE
Wait for ACF before registering fields

### ISSUE THREAD

**Issue by lhall-amphibee** [AmphiBee/MenuItemTypeMaker#3]
`registerFields` should be fired on the acf/init hook to prevent errors

**Comment by ogorzalka** [comment]
When working on the wrapper, it didn't work with the hook. Are you sure that the field work with the hook addition @lhall-amphibee ?

**Comment by lhall-amphibee** [comment]
Actually it was a bad idea. Let's revert this !

**Comment by ogorzalka** [comment]
🙂
